version: "3"
services:


  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'

  event:
    build:
      dockerfile: Dockerfile
      context: ./event
    container_name: event
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "rabbitmq"
    volumes:
      - .:/app
      - /app/event/node_modules

  payment:
    build:
      dockerfile: Dockerfile
      context: ./payment
    container_name: payment
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - "rabbitmq"
    volumes:
      - .:/app
      - /app/payment/node_modules

  customer:
    build:
      dockerfile: Dockerfile
      context: ./customer
    container_name: customer
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "rabbitmq"
    volumes:
      - .:/app/
      - /app/customer/node_modules

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - event
      - payment
      - customer
    ports:
      - 80:80
