exports.eventList=[
    {
        _id:"1",
        title:"bithday",
        customerId:"1"
    },
    {
        _id:"2",
        title:"wedding",
        customerId:"4"
    },
    {
        _id:"3",
        title:"bithday",
        customerId:"5"
    },
    {
        _id:"4",
        title:"party",
        customerId:"2"
    },
    {
        _id:"5",
        title:"anavesery",
        customerId:"2"
    },
    {
        _id:"6",
        title:"party",
        customerId:"3"
    },
    {
        _id:"7",
        title:"dinner",
        customerId:"2"
    },
    {
        _id:"8",
        title:"party",
        customerId:"4"
    },
    {
        _id:"9",
        title:"bithday",
        customerId:"5"
    },
    
]